app/app.py
from flask import Flask
from config import Configuration

from posts.blueprint import posts


app = Flask(__name__)
app.config.from_object(Configuration)

app.register_blueprint(posts, url_prefix="/blog")

app/main.py
from app import app 
import view

if __name__ == '__main__':
    app.run()

app/posts/blueprint.py
from flask import Blueprint
from flask import render_template

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/')
def index():
    return render_template('posts/index.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>
        {% block title %}

        {% endblock %} | Flask app
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-inverse bg-light">
        <a class="navbar-brand" href=" {{ url_for('index') }} ">Flask</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon">Hello</span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('posts.index') }}">Blog <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
           
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    <div class="container">
        <div class="row">
            <h1>
                {% block content_title %}
                
                {% endblock %}

            </h1>
        </div>    
            {% block content %}

            {% endblock %}

        
    </div>    

</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index page
{% endblock %}

{% block content_title %}
    How are you?
{% endblock %}

{% block content %}
    Some content
{% endblock %}